In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import plotly.graph_objs as go
from plotly.offline import iplot
sns.set()
pd.options.display.max_columns = 999

In [2]:
data = pd.read_csv("ORDS.QA(1).csv")

In [3]:
data.shape

(3064, 7)

In [4]:
data.head

<bound method NDFrame.head of             Date      Open      High       Low     Close  Adj Close     Volume
0     2010-02-22  9.871794  9.935897  9.871794  9.916666   5.667912   111306.0
1     2010-02-23  9.929486  9.935897  9.858974  9.891025   5.653255  1124120.0
2     2010-02-24  9.929486  9.935897  9.846154  9.871794   5.642265  1834232.0
3     2010-02-25  9.839743  9.935897  9.807692  9.916666   5.667912   505284.0
4     2010-02-28  9.929486  9.935897  9.878205  9.916666   5.667912   213345.0
...          ...       ...       ...       ...       ...        ...        ...
3059  2022-03-22  7.350000  7.350000  7.203000  7.300000   7.300000   960254.0
3060  2022-03-23  7.209000  7.245000  7.190000  7.240000   7.240000   680496.0
3061  2022-03-24  7.239000  7.239000  7.115000  7.232000   7.232000   907565.0
3062  2022-03-27  7.232000  7.232000  7.101000  7.188000   7.188000  1008788.0
3063  2022-03-28  7.116000  7.117000  7.097000  7.100000   7.100000  1884659.0

[3064 rows x 7 columns]>

In [5]:
print(data.columns)

Index(['Date', 'Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume'], dtype='object')

In [6]:
data.head()

         Date      Open      High       Low     Close  Adj Close     Volume
0  2010-02-22  9.871794  9.935897  9.871794  9.916666   5.667912   111306.0
1  2010-02-23  9.929486  9.935897  9.858974  9.891025   5.653255  1124120.0
2  2010-02-24  9.929486  9.935897  9.846154  9.871794   5.642265  1834232.0
3  2010-02-25  9.839743  9.935897  9.807692  9.916666   5.667912   505284.0
4  2010-02-28  9.929486  9.935897  9.878205  9.916666   5.667912   213345.0

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3064 entries, 0 to 3063
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       3064 non-null   object
 1   Open       3038 non-null   float64
 2   High       3038 non-null   float64
 3   Low        3038 non-null   float64
 4   Close      3038 non-null   float64
 5   Adj Close  3038 non-null   float64
 6   Volume     3038 non-null   float64
dtypes: float64(6), object(1)
memory usage: 167.7+ KB

In [8]:
data.describe()

,Open,High,Low,Close,Adj Close,Volume
count,3038.000000,3038.000000,3038.000000,3038.000000,3038.000000,3.038000e+03
mean,9.677841,9.760014,9.598441,9.681249,6.919068,1.105907e+06
std,4.344916,4.350302,4.338450,4.345271,2.412126,1.359410e+06
min,4.743589,5.179000,4.805000,5.097000,4.379930,0.000000e+00
25%,7.240000,7.300000,7.180000,7.240000,6.054258,3.675402e+05
50%,9.457564,9.550000,9.350000,9.450000,6.733011,7.743175e+05
75%,11.359744,11.415384,11.307692,11.369230,7.347919,1.388647e+06
max,116.666664,116.666664,116.666664,116.666664,69.754166,2.979510e+07

In [9]:
data['Date'] = pd.to_datetime(data['Date'])

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3064 entries, 0 to 3063
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       3064 non-null   datetime64[ns]
 1   Open       3038 non-null   float64
 2   High       3038 non-null   float64
 3   Low        3038 non-null   float64
 4   Close      3038 non-null   float64
 5   Adj Close  3038 non-null   float64
 6   Volume     3038 non-null   float64
dtypes: datetime64[ns](1), float64(6)
memory usage: 167.7 KB

In [12]:
print(data.isnull().sum())

Date          0
Open         26
High         26
Low          26
Close        26
Adj Close    26
Volume       26
dtype: int64

In [13]:
data = data.dropna()

In [14]:
print(data.isnull().sum())

Date         0
Open         0
High         0
Low          0
Close        0
Adj Close    0
Volume       0
dtype: int64

In [15]:
data = data.sort_values(by='Date')

### Calculating Daily Returns

### to show how much the stock price changes from one day to the next (in %)

In [18]:
data['Daily Return'] = data['Adj Close'].pct_change()

### Calculating Moving Average

#### 7-day moving average:

In [19]:
data['MA7'] = data['Adj Close'].rolling(window=7).mean()

#### 30-day movng average

In [20]:
data['MA30'] = data['Adj Close'].rolling(window=30).mean()

### Volatility (Risk Measurement)

In [21]:
#### high value -> price is unstable
#### Low value -> stock is stable

In [22]:
data['Volatility'] = data['Daily Return'].rolling(window=7).std()

### Volume Trend
#### To check when trading activity increases

In [23]:
data['Volume_MA7'] = data['Volume'].rolling(window=7).mean()

In [24]:
data = data.dropna()

In [25]:
data.head()

,Date,Open,High,Low,Close,Adj Close,Volume,Daily Return,MA7,MA30,Volatility,Volume_MA7
32,2010-04-07,9.871794,10.096153,9.871794,10.000000,5.715540,2434972.0,0.016949,5.580503,5.518550,0.012367,1.051274e+06
33,2010-04-08,9.871794,10.096153,9.871794,10.000000,5.715540,2434972.0,0.000000,5.606673,5.520138,0.010047,1.329623e+06
34,2010-04-11,10.256410,10.352564,10.249999,10.262821,5.865758,2523081.0,0.026282,5.655873,5.527221,0.012330,1.617120e+06
35,2010-04-12,10.384615,10.384615,10.230769,10.275641,5.873086,2433990.0,0.001249,5.710830,5.534915,0.011138,1.928779e+06
36,2010-04-13,10.243589,10.320512,10.237179,10.269230,5.869420,3347354.0,-0.000624,5.757413,5.541632,0.011806,2.013610e+06

In [26]:
data.to_csv('ooredoo_cleaned.csv')

In [30]:
data.to_excel("ooredoo_cleaned.xlsx", index=False)